import female_1 from "./studentPhotos/female_1.jpg";
import female_2 from "./studentPhotos/female_2.jpg";
import female_3 from "./studentPhotos/female_3.jpg";
import female_4 from "./studentPhotos/female_4.jpg";
import female_5 from "./studentPhotos/female_5.jpg";
import female_6 from "./studentPhotos/female_6.jpg";
import male_1 from "./studentPhotos/male_1.jpg";
import male_2 from "./studentPhotos/male_2.jpg";
import male_3 from "./studentPhotos/male_3.jpg";
import male_4 from "./studentPhotos/male_4.jpg";

const personalData = [
  {
    id: 1,
    firstName: "Evelyn",
    lastName: "Minnette",
    age: 23,
    phone: "4863663542",
    email: "eminnette0@dagondesign.com",
    photo: female_1,
  },
  {
    id: 2,
    firstName: "Aranka",
    lastName: "Dilleston",
    age: 43,
    phone: "1212938696",
    email: "adilleston1@cbsnews.com",
    photo: female_2,
  },
  {
    id: 3,
    firstName: "Richard",
    lastName: "Billison",
    age: 28,
    phone: "9765185630",
    email: "fbillison2@photobucket.com",
    photo: male_1,
  },
  {
    id: 4,
    firstName: "Hector",
    lastName: "Glazzard",
    age: 19,
    phone: "2894456768",
    email: "rglazzard3@printfriendly.com",
    photo: male_2,
  },
  {
    id: 5,
    firstName: "Martina",
    lastName: "Schlagman",
    age: 37,
    phone: "2429924343",
    email: "mschlagman4@auda.org.au",
    photo: female_3,
  },
  {
    id: 6,
    firstName: "Maurits",
    lastName: "Kenworthy",
    age: 35,
    phone: "4678187487",
    email: "mkenworthy5@yellowpages.com",
    photo: male_4,
  },
  {
    id: 7,
    firstName: "Rahima",
    lastName: "Slate",
    age: 22,
    phone: "5214068238",
    email: "rslate6@kickstarter.com",
    photo: female_4,
  },
  {
    id: 8,
    firstName: "Sandra",
    lastName: "Elman",
    age: 29,
    phone: "4689139896",
    email: "selman7@blogger.com",
    photo: female_5,
  },
  {
    id: 9,
    firstName: "Wietske",
    lastName: "Bettenson",
    age: 42,
    phone: "8473074082",
    email: "wbettenson8@unicef.org",
    photo: female_6,
  },
  {
    id: 10,
    firstName: "Oscar",
    lastName: "Casero",
    age: 27,
    phone: "4423701095",
    email: "ocasero9@acquirethisname.com",
    photo: male_3,
  },
];

const ratingData = [
  {
    studentName: "Evelyn",
    assignmentName: "SCRUM",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D1-1",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D2-1",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D2-2",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D2-3",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D2-4",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D2-5",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D3-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D3-2",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D3-4",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D3-5",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D3 - Project - Guess-the-number",
    difficultyRating: 5,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D4-1",
    difficultyRating: 4,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D4 - Project - Kleurentoggle",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W1D5 - Project - Galgje",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W2D1-1",
    difficultyRating: 1,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W2D1-2",
    difficultyRating: 2,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W2D2-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W2D2-2",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W2D2-3",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W2D3-1",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W2D3-2",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W2D3-3",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W2D4-1",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W2D4-2",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W2D4-3",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W2D5 - Project - Filmzoeker",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D1-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D1-2",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D1-3",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D1-4",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D2-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D2-2",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D2-3",
    difficultyRating: 3,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D3-1",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D3-2",
    difficultyRating: 4,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D3-3",
    difficultyRating: 3,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D3-4",
    difficultyRating: 4,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D4-1",
    difficultyRating: 5,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D4-2",
    difficultyRating: 1,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W3D5 - Project - Todo-List",
    difficultyRating: 2,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W4D2-1",
    difficultyRating: 1,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W4D2-2",
    difficultyRating: 1,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W4D2-3",
    difficultyRating: 1,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W4D2-4",
    difficultyRating: 1,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W4D3-1",
    difficultyRating: 1,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W4D3-2",
    difficultyRating: 1,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W4D3-3",
    difficultyRating: 1,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W4D3-4",
    difficultyRating: 1,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W4D3-5",
    difficultyRating: 1,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W4D3 - Project - Next-Level CSS",
    difficultyRating: 1,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W5D4-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W5D5 - Project - Lil_Playlist",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W6D1-1",
    difficultyRating: 5,
    funRating: 5,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W6D2-1",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Evelyn",
    assignmentName: "W6D2 - Project - Eindopdracht",
    difficultyRating: 5,
    funRating: 5,
  },
  {
    studentName: "Aranka",
    assignmentName: "SCRUM",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D1-1",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D2-1",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D2-2",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D2-3",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D2-4",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D2-5",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D3-1",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D3-2",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D3-4",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D3-5",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D3 - Project - Guess-the-number",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D4-1",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D4 - Project - Kleurentoggle",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W1D5 - Project - Galgje",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W2D1-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Aranka",
    assignmentName: "W2D1-2",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Aranka",
    assignmentName: "W2D2-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Aranka",
    assignmentName: "W2D2-2",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Aranka",
    assignmentName: "W2D2-3",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Aranka",
    assignmentName: "W2D3-1",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W2D3-2",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W2D3-3",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W2D4-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Aranka",
    assignmentName: "W2D4-2",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W2D4-3",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W2D5 - Project - Filmzoeker",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D1-1",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D1-2",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D1-3",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D1-4",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D2-1",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D2-2",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D2-3",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D3-1",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D3-2",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D3-3",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D3-4",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D4-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D4-2",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W3D5 - Project - Todo-List",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W4D2-1",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W4D2-2",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W4D2-3",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W4D2-4",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Aranka",
    assignmentName: "W4D3-1",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W4D3-2",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Aranka",
    assignmentName: "W4D3-3",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W4D3-4",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W4D3-5",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W4D3 - Project - Next-Level CSS",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Aranka",
    assignmentName: "W5D4-1",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Aranka",
    assignmentName: "W5D5 - Project - Lil_Playlist",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W6D1-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Aranka",
    assignmentName: "W6D2-1",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Aranka",
    assignmentName: "W6D2 - Project - Eindopdracht",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "SCRUM",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D1-1",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D2-1",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D2-2",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D2-3",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D2-4",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D2-5",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D3-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D3-2",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D3-4",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D3-5",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D3 - Project - Guess-the-number",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D4-1",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D4 - Project - Kleurentoggle",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Richard",
    assignmentName: "W1D5 - Project - Galgje",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W2D1-1",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W2D1-2",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Richard",
    assignmentName: "W2D2-1",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Richard",
    assignmentName: "W2D2-2",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W2D2-3",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W2D3-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Richard",
    assignmentName: "W2D3-2",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W2D3-3",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Richard",
    assignmentName: "W2D4-1",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W2D4-2",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Richard",
    assignmentName: "W2D4-3",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Richard",
    assignmentName: "W2D5 - Project - Filmzoeker",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D1-1",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D1-2",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D1-3",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D1-4",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D2-1",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D2-2",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D2-3",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D3-1",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D3-2",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D3-3",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D3-4",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D4-1",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D4-2",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W3D5 - Project - Todo-List",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W4D2-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W4D2-2",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Richard",
    assignmentName: "W4D2-3",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W4D2-4",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W4D3-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W4D3-2",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Richard",
    assignmentName: "W4D3-3",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W4D3-4",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W4D3-5",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Richard",
    assignmentName: "W4D3 - Project - Next-Level CSS",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W5D4-1",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Richard",
    assignmentName: "W5D5 - Project - Lil_Playlist",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Richard",
    assignmentName: "W6D1-1",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Richard",
    assignmentName: "W6D2-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Richard",
    assignmentName: "W6D2 - Project - Eindopdracht",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "SCRUM",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D1-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D2-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D2-2",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D2-3",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D2-4",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D2-5",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D3-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D3-2",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D3-4",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D3-5",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D3 - Project - Guess-the-number",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D4-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D4 - Project - Kleurentoggle",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Hector",
    assignmentName: "W1D5 - Project - Galgje",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W2D1-1",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W2D1-2",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Hector",
    assignmentName: "W2D2-1",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Hector",
    assignmentName: "W2D2-2",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Hector",
    assignmentName: "W2D2-3",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Hector",
    assignmentName: "W2D3-1",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W2D3-2",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Hector",
    assignmentName: "W2D3-3",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Hector",
    assignmentName: "W2D4-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W2D4-2",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W2D4-3",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Hector",
    assignmentName: "W2D5 - Project - Filmzoeker",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D1-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D1-2",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D1-3",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D1-4",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D2-1",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D2-2",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D2-3",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D3-1",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D3-2",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D3-3",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D3-4",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D4-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D4-2",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W3D5 - Project - Todo-List",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W4D2-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W4D2-2",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W4D2-3",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Hector",
    assignmentName: "W4D2-4",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Hector",
    assignmentName: "W4D3-1",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Hector",
    assignmentName: "W4D3-2",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W4D3-3",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W4D3-4",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Hector",
    assignmentName: "W4D3-5",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Hector",
    assignmentName: "W4D3 - Project - Next-Level CSS",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W5D4-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Hector",
    assignmentName: "W5D5 - Project - Lil_Playlist",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W6D1-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Hector",
    assignmentName: "W6D2-1",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Hector",
    assignmentName: "W6D2 - Project - Eindopdracht",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "SCRUM",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D1-1",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D2-1",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D2-2",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D2-3",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D2-4",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D2-5",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D3-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D3-2",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D3-4",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D3-5",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D3 - Project - Guess-the-number",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D4-1",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D4 - Project - Kleurentoggle",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Martina",
    assignmentName: "W1D5 - Project - Galgje",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W2D1-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W2D1-2",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Martina",
    assignmentName: "W2D2-1",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W2D2-2",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Martina",
    assignmentName: "W2D2-3",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W2D3-1",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Martina",
    assignmentName: "W2D3-2",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W2D3-3",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Martina",
    assignmentName: "W2D4-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W2D4-2",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W2D4-3",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W2D5 - Project - Filmzoeker",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D1-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D1-2",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D1-3",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D1-4",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D2-1",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D2-2",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D2-3",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D3-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D3-2",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D3-3",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D3-4",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D4-1",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D4-2",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W3D5 - Project - Todo-List",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Martina",
    assignmentName: "W4D2-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W4D2-2",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Martina",
    assignmentName: "W4D2-3",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W4D2-4",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W4D3-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W4D3-2",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Martina",
    assignmentName: "W4D3-3",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W4D3-4",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W4D3-5",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Martina",
    assignmentName: "W4D3 - Project - Next-Level CSS",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W5D4-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W5D5 - Project - Lil_Playlist",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W6D1-1",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Martina",
    assignmentName: "W6D2-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Martina",
    assignmentName: "W6D2 - Project - Eindopdracht",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Maurits",
    assignmentName: "SCRUM",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D1-1",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D2-1",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D2-2",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D2-3",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D2-4",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D2-5",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D3-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D3-2",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D3-4",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D3-5",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D3 - Project - Guess-the-number",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D4-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D4 - Project - Kleurentoggle",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W1D5 - Project - Galgje",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Maurits",
    assignmentName: "W2D1-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W2D1-2",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W2D2-1",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Maurits",
    assignmentName: "W2D2-2",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W2D2-3",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Maurits",
    assignmentName: "W2D3-1",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Maurits",
    assignmentName: "W2D3-2",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W2D3-3",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W2D4-1",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W2D4-2",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Maurits",
    assignmentName: "W2D4-3",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W2D5 - Project - Filmzoeker",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D1-1",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D1-2",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D1-3",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D1-4",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D2-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D2-2",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D2-3",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D3-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D3-2",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D3-3",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D3-4",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D4-1",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D4-2",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W3D5 - Project - Todo-List",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Maurits",
    assignmentName: "W4D2-1",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W4D2-2",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Maurits",
    assignmentName: "W4D2-3",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W4D2-4",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W4D3-1",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W4D3-2",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Maurits",
    assignmentName: "W4D3-3",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Maurits",
    assignmentName: "W4D3-4",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W4D3-5",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Maurits",
    assignmentName: "W4D3 - Project - Next-Level CSS",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W5D4-1",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W5D5 - Project - Lil_Playlist",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Maurits",
    assignmentName: "W6D1-1",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Maurits",
    assignmentName: "W6D2-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Maurits",
    assignmentName: "W6D2 - Project - Eindopdracht",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Rahima",
    assignmentName: "SCRUM",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D1-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D2-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D2-2",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D2-3",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D2-4",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D2-5",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D3-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D3-2",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D3-4",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D3-5",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D3 - Project - Guess-the-number",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D4-1",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D4 - Project - Kleurentoggle",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W1D5 - Project - Galgje",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Rahima",
    assignmentName: "W2D1-1",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W2D1-2",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W2D2-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W2D2-2",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W2D2-3",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W2D3-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W2D3-2",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W2D3-3",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W2D4-1",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W2D4-2",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W2D4-3",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Rahima",
    assignmentName: "W2D5 - Project - Filmzoeker",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D1-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D1-2",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D1-3",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D1-4",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D2-1",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D2-2",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D2-3",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D3-1",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D3-2",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D3-3",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D3-4",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D4-1",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D4-2",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Rahima",
    assignmentName: "W3D5 - Project - Todo-List",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W4D2-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W4D2-2",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Rahima",
    assignmentName: "W4D2-3",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Rahima",
    assignmentName: "W4D2-4",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W4D3-1",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W4D3-2",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W4D3-3",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Rahima",
    assignmentName: "W4D3-4",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W4D3-5",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W4D3 - Project - Next-Level CSS",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Rahima",
    assignmentName: "W5D4-1",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Rahima",
    assignmentName: "W5D5 - Project - Lil_Playlist",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Rahima",
    assignmentName: "W6D1-1",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W6D2-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Rahima",
    assignmentName: "W6D2 - Project - Eindopdracht",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Sandra",
    assignmentName: "SCRUM",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D1-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D2-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D2-2",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D2-3",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D2-4",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D2-5",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D3-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D3-2",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D3-4",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D3-5",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D3 - Project - Guess-the-number",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D4-1",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D4 - Project - Kleurentoggle",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W1D5 - Project - Galgje",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W2D1-1",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Sandra",
    assignmentName: "W2D1-2",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W2D2-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W2D2-2",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W2D2-3",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W2D3-1",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Sandra",
    assignmentName: "W2D3-2",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Sandra",
    assignmentName: "W2D3-3",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Sandra",
    assignmentName: "W2D4-1",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W2D4-2",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W2D4-3",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Sandra",
    assignmentName: "W2D5 - Project - Filmzoeker",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D1-1",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D1-2",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D1-3",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D1-4",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D2-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D2-2",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D2-3",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D3-1",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D3-2",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D3-3",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D3-4",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D4-1",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D4-2",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Sandra",
    assignmentName: "W3D5 - Project - Todo-List",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Sandra",
    assignmentName: "W4D2-1",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W4D2-2",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Sandra",
    assignmentName: "W4D2-3",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W4D2-4",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W4D3-1",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Sandra",
    assignmentName: "W4D3-2",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W4D3-3",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W4D3-4",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W4D3-5",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W4D3 - Project - Next-Level CSS",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W5D4-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Sandra",
    assignmentName: "W5D5 - Project - Lil_Playlist",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Sandra",
    assignmentName: "W6D1-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Sandra",
    assignmentName: "W6D2-1",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Sandra",
    assignmentName: "W6D2 - Project - Eindopdracht",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "SCRUM",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D1-1",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D2-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D2-2",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D2-3",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D2-4",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D2-5",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D3-1",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D3-2",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D3-4",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D3-5",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D3 - Project - Guess-the-number",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D4-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D4 - Project - Kleurentoggle",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Wietske",
    assignmentName: "W1D5 - Project - Galgje",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Wietske",
    assignmentName: "W2D1-1",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "W2D1-2",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "W2D2-1",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Wietske",
    assignmentName: "W2D2-2",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W2D2-3",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W2D3-1",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "W2D3-2",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "W2D3-3",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Wietske",
    assignmentName: "W2D4-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "W2D4-2",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W2D4-3",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Wietske",
    assignmentName: "W2D5 - Project - Filmzoeker",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D1-1",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D1-2",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D1-3",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D1-4",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D2-1",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D2-2",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D2-3",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D3-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D3-2",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D3-3",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D3-4",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D4-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D4-2",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Wietske",
    assignmentName: "W3D5 - Project - Todo-List",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W4D2-1",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Wietske",
    assignmentName: "W4D2-2",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W4D2-3",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Wietske",
    assignmentName: "W4D2-4",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Wietske",
    assignmentName: "W4D3-1",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "W4D3-2",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Wietske",
    assignmentName: "W4D3-3",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W4D3-4",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Wietske",
    assignmentName: "W4D3-5",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Wietske",
    assignmentName: "W4D3 - Project - Next-Level CSS",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Wietske",
    assignmentName: "W5D4-1",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "W5D5 - Project - Lil_Playlist",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Wietske",
    assignmentName: "W6D1-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "W6D2-1",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Wietske",
    assignmentName: "W6D2 - Project - Eindopdracht",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "SCRUM",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D1-1",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D2-1",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D2-2",
    difficultyRating: 1,
    funRating: 3,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D2-3",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D2-4",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D2-5",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D3-1",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D3-2",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D3-4",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D3-5",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D3 - Project - Guess-the-number",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D4-1",
    difficultyRating: 4,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D4 - Project - Kleurentoggle",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W1D5 - Project - Galgje",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W2D1-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W2D1-2",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W2D2-1",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W2D2-2",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W2D2-3",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W2D3-1",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Oscar",
    assignmentName: "W2D3-2",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W2D3-3",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W2D4-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W2D4-2",
    difficultyRating: 4,
    funRating: 3,
  },
  {
    studentName: "Oscar",
    assignmentName: "W2D4-3",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W2D5 - Project - Filmzoeker",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D1-1",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D1-2",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D1-3",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D1-4",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D2-1",
    difficultyRating: 1,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D2-2",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D2-3",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D3-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D3-2",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D3-3",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D3-4",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D4-1",
    difficultyRating: 2,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D4-2",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W3D5 - Project - Todo-List",
    difficultyRating: 3,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W4D2-1",
    difficultyRating: 2,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W4D2-2",
    difficultyRating: 3,
    funRating: 3,
  },
  {
    studentName: "Oscar",
    assignmentName: "W4D2-3",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W4D2-4",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W4D3-1",
    difficultyRating: 3,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W4D3-2",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Oscar",
    assignmentName: "W4D3-3",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W4D3-4",
    difficultyRating: 3,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W4D3-5",
    difficultyRating: 2,
    funRating: 3,
  },
  {
    studentName: "Oscar",
    assignmentName: "W4D3 - Project - Next-Level CSS",
    difficultyRating: 4,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W5D4-1",
    difficultyRating: 2,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W5D5 - Project - Lil_Playlist",
    difficultyRating: 1,
    funRating: 2,
  },
  {
    studentName: "Oscar",
    assignmentName: "W6D1-1",
    difficultyRating: 4,
    funRating: 4,
  },
  {
    studentName: "Oscar",
    assignmentName: "W6D2-1",
    difficultyRating: 1,
    funRating: 1,
  },
  {
    studentName: "Oscar",
    assignmentName: "W6D2 - Project - Eindopdracht",
    difficultyRating: 3,
    funRating: 3,
  },
];

export { ratingData, personalData };
